FitnessClubApp/Models/Coach.cs
namespace FitnessClubApp.Models
{
    public class Coach
    {
        
        public int CoachId { get; set; }
        public string CoachName { get; set; }
        public string CoachType { get; set; }
        public string Email { get; set; }
        public int Contact { get; set; }

        public string CoachImage { get; set; }





    }
}

FitnessClubApp/Models/CoachRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FitnessClubApp.Models
{
    public class CoachRepository:ICoachRepository
    {
        private static List<Coach> _coaches = new List<Coach>();
      //  {
      //      new Coach(){  CoachId = "C001",CoachName = "Suresh",CoachType = "WorkOut",Email = "sureshcoach@cloudkampus.com",Contact = 12345679 },

      //      new Coach() { CoachId="C002",CoachName="Amita",CoachType="Workout",Email="Amita@cloudkampus.com",Contact=123456788},

      //new Coach() { CoachId = "C003", CoachName = "Bhuvana", CoachType = "Diet", Email = "diet_Bhuvi@cloudkampus.com", Contact = 127856788 },
      //  new Coach() { CoachId = "C004", CoachName = "Rekha", CoachType = "Diet", Email = "Rehka@cloudkampus.com", Contact = 1237486788 }
      //  };

        public List<Coach> GetCoaches()
        {
            return _coaches;
        }

   
        public  int AddNewCoach(Coach coach)
        {
            _coaches.Add(coach);
            return 1;
        }

        public Coach GetCoach(int coach)
        {
            throw new NotImplementedException();
        }

        public int DeleteCoach(int id)
        {
            throw new NotImplementedException();
        }
    }
}

FitnessClubApp/Models/DBHelper.cs
using System.Data.SqlClient;


namespace FitnessClubApp.Models
{
    public class DBHelper : ICoachRepository
    {
        

        string conString = "Server=Dhivya-pc\\SqlExpress;Database=FitnessTracker;integrated security=true";
        SqlConnection con;
        SqlCommand com;
        SqlDataReader reader;

        public DBHelper()
        {
            con = new SqlConnection(conString);
            con.Open();
        }


        public int AddNewCoach(Coach coach)
        {
            string cmdText = "insert into Coaches(CoachName, CoachType, Email, Contact) values('" + coach.CoachName + "','" + coach.CoachType + "','" + coach.Email + "'," + coach.Contact + ")";
            com = new SqlCommand(cmdText, con);
            return com.ExecuteNonQuery();
}

        public Coach GetCoach(int id)
        {
            Coach c = GetCoaches().FirstOrDefault(cc => cc.CoachId == id);
                return c;
        }

        public List<Coach> GetCoaches()
        {
            List<Coach> coaches = new List<Coach>();
            com = new SqlCommand("Select * from coaches where isActive=1", con);
            reader = com.ExecuteReader();
            while(reader.Read())
            {
                Coach coach = new Coach();
                coach.CoachId = reader.GetInt32(0);
                coach.CoachName = reader.GetString(1);
                coach.CoachType = reader.GetString(2);
                coach.Email = reader.GetString(3);
                coach.Contact = reader.GetInt32(4);
                coach.CoachImage = reader.GetString(5);
                coaches.Add(coach);
            }

            return coaches;
            
        }
  
    public int DeleteCoach(int id)
        {
            com = new SqlCommand("update coaches set isActive=0 where coachId=" + id, con);
            return com.ExecuteNonQuery();
        }
    
    }
}

FitnessClubApp/Models/ICoachRepository.cs
namespace FitnessClubApp.Models
{
    public interface ICoachRepository
    {
        List<Coach> GetCoaches();
        Coach GetCoach(int coach);

        int AddNewCoach(Coach coach);
        int DeleteCoach(int id);
    }
}

FitnessClubApp/Pages/AddCoach.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class AddCoachModel : PageModel
    {
        DBHelper repo= new DBHelper();

        [BindProperty]
        public Coach Coach { get; set; }
        public void OnGet()
        {
        }

        public void OnPost()
        {
            repo.AddNewCoach(Coach);
        }
    }
}

FitnessClubApp/Pages/CoachStory.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class CoachStoryModel : PageModel
    {


        DBHelper repo = new DBHelper();
        public Coach CoachPro { get; set; }
        public void OnGet(int id)
        {

          

       CoachPro=  repo.GetCoach(id);



        }
    }
}

FitnessClubApp/Pages/Delete.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class DeleteModel : PageModel
    {
        DBHelper repo = new DBHelper();
        public Coach CoachPro { get; set; }
        public void OnGet(int id)
        {



            CoachPro = repo.GetCoach(id);



        }
    }
}

FitnessClubApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class IndexModel : PageModel
    {
        private string pageTitle;

        public string PageTitle
        {
            get { return pageTitle; }
            set { pageTitle = value; }
        }

        public string SubTitle { get; set; }

        public void OnGet()
        {
            PageTitle = "Fitness Club -CK";
            SubTitle = "Home Page";

            ViewData["Message"] = "Hello Welcome to Fitness";//Key-value 
        }
    }
}

FitnessClubApp/Pages/NewCoach.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class NewCoachModel : PageModel
    {
        CoachRepository repo = new CoachRepository();
        [BindProperty]
        public Coach CoachPro { get; set; }
       
        public void OnGet()
        {

        }


       

        public void OnPost()
        {

       
            CoachPro.CoachId = repo.GetCoaches().Count+1;
               repo.AddNewCoach(CoachPro);
            
        }
    }
}

FitnessClubApp/Pages/Trainer.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Collections.Generic;

namespace FitnessClubApp.Pages
{
    public class TrainerModel : PageModel
    {
        DBHelper repo = new DBHelper();

        public List<Coach> Coaches { get; set; }


        public void OnGet()
        {

           

            Coaches = repo.GetCoaches();
               }
    }
}

FitnessClubApp/Pages/Yes.cshtml.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FitnessClubApp.Pages
{
    public class YesModel : PageModel
    {
        DBHelper repo = new DBHelper();
        public IActionResult OnGet( int id)
        {
            repo.DeleteCoach(id);
            return Redirect("Trainer");
        }
    }
}

FitnessClubApp/ViewComponents/CoachDetailViewComponent.cs
using FitnessClubApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FitnessClubApp.ViewComponents
{
    public class CoachDetailViewComponent:ViewComponent
    {
        DBHelper repo = new DBHelper();

        public IViewComponentResult Invoke(int id)
        {
            var coach = repo.GetCoach(id);
            return View(coach);
        }
    }
}

FitnessClubApp/Pages/AddCoach.cshtml
@page
@model FitnessClubApp.Pages.AddCoachModel
@{
}

<form method="post">
    <table>
        <tr>
            <td>Coach Name :</td><td><input asp-for="Coach.CoachName" /></td>
        </tr>
        <tr>
            <td>Coach Type :</td><td><input asp-for="Coach.CoachType" /></td>
        </tr>
        <tr>
            <td>Coach Email :</td><td><input asp-for="Coach.Email" /></td>
        </tr>
        <tr>
            <td>Coach Phone :</td><td><input asp-for="Coach.Contact" /></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" class="btn btn-info"/>
            </td>
            </tr>
    </table>
</form>

FitnessClubApp/Pages/CoachStory.cshtml
@page
@model FitnessClubApp.Pages.CoachStoryModel
@{
}

<div class="card w-25">
      @await Component.InvokeAsync("CoachDetail",new {id=@Model.CoachPro.CoachId})

    <div class="card-footer">
        <a asp-page="Trainer" class="btn btn-secondary">Back to Coaches</a>
    </div>
</div>

FitnessClubApp/Pages/Delete.cshtml
@page
@model FitnessClubApp.Pages.DeleteModel
@{
}

<div class="card w-25">
   @await Component.InvokeAsync("CoachDetail",new {id=@Model.CoachPro.CoachId})
    <div class="card-footer">
  <p class="alert alert-success">Are you sure to delete the Coach Detail </p>      <a asp-page="Yes" asp-route-id=@Model.CoachPro.CoachId class="btn btn-secondary">Yes</a>
  <a asp-page="Trainer" class="btn btn-danger">No</a>
    </div>
</div>

FitnessClubApp/Pages/Index.cshtml
@page
@model FitnessClubApp.Pages.IndexModel //IndexModel class is made available to this .csHTml file throu' @model directive 
@{
}

<div class="text-center display-4">
@Model.PageTitle -- @Model.SubTitle






</div>
<p class="text-center w-25 alert alert-info">@ViewData["Message"]</p>

FitnessClubApp/Pages/NewCoach.cshtml
@page
@model FitnessClubApp.Pages.NewCoachModel
@{
}

<form method="post" >
<table class="m-5">
    <tr>
        <td>Coach Name :</td><td><input asp-for="CoachPro.CoachName" id="txtName" name="txtName"/></td>

    </tr>
     <tr>
        <td>Coach Type :</td><td><input asp-for="CoachPro.CoachType" id="txtType" name="txtType"/></td>
    </tr>
     <tr>
        <td>Coach Email :</td><td><input asp-for="CoachPro.Email" id="txtEmail" name="txtEmail"/></td>
    </tr>
     <tr>
        <td>Coach Phone :</td><td><input asp-for="CoachPro.Contact" id="txtPhone" name="txtPhone"/></td>
    </tr>
    <tr>
        <td colspan=2><input type="submit" class="btn btn-primary"/></td>
    </tr>
</table>
</form>

FitnessClubApp/Pages/Shared/Components/CoachDetail/Default.cshtml
@model FitnessClubApp.Models.Coach

 <div class="card-body">
        <img class="card-img" src=@Model.CoachImage alt="Coach"/>
        <p class="card-text">@Model.CoachName</p>
        <p class="card-text">@Model.CoachType
        </p>
        <p class="card-text">@Model.Email</p>
        <p class="card-text">@Model.Contact</p>

    </div>

FitnessClubApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href='/lib/bootstrap/css/bootstrap.min.css' rel="stylesheet"/>
</head>
<body>
     <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand"  asp-page="/Index">Fitness Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Trainer">Coaches</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
            </nav>
            </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>

FitnessClubApp/Pages/Trainer.cshtml
@page
@model FitnessClubApp.Pages.TrainerModel
@{
}
<div class="text-center">
    <p class=display-3>This is the Coaches Detail </p>

    <div class="container">
        <div class="row">

            @foreach(var item in @Model.Coaches)
            {
            <div class="col-sm-3">
            @await Component.InvokeAsync("CoachDetail",new {id=@item.CoachId})

                <div class="card-footer">
                    <a asp-page="CoachStory" asp-route-id=@item.CoachId class="btn btn-primary">View</a>
                        <a asp-page="Edit" asp-route-id=@item.CoachId class="btn btn-secondary">Edit</a>
                            <a asp-page="Delete" asp-route-id=@item.CoachId class="btn btn-danger">Delete</a>
                    </div>
            </div>    
            
            
            }
            </div>
            </div>
            </div>
 

FitnessClubApp/Pages/Yes.cshtml
@page
@model FitnessClubApp.Pages.YesModel
@{
}